name = "pbepack"
version = "0.1.0"
license = "mit"
author = "HugoMVale"
maintainer = "57530119+HugoMVale@users.noreply.github.com"
copyright = "Copyright 2022, HugoMVale"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
stdlib = { git = "https://github.com/HugoMVale/stdlib", branch = "stdlib-fpm" }
hrweno = { git = "https://github.com/HugoMVale/HR-WENO", branch = "main" }
odepack = { git = "https://github.com/Nicholaswogan/odepack", branch = "main"}

[dev-dependencies]
test-drive = { git = "https://github.com/zoziha/test-drive", branch = "add-support-array" }
